export { default as Login } from './Login.vue'
export { default as Home } from './Home.vue'
export { default as VideoC } from './VideoChannel.vue'
export { default as HomeDetail } from './HomeDetail.vue'
export { default as Register } from './Register.vue'
export { default as CreateSellHome } from './CreateSellHome.vue'
export { default as Profile } from './Profile.vue'
